### ISSUE TITLE
Error on https

### ISSUE THREAD

**Issue by gallegostronica** [ilias-sp/Twitch-Chat-Bot-PHP#2]
Hi.

I'm trying your bot (nice job) but I had an error related to php.ini, I'm telling you in case you want to add it to the instructions. I was getting this error:

"Unable to find the wrapper https"

I had to add a new extension in php.ini (extension=php_openssl.dll) in order to avoid it.

Thanks for sharing your job.

**Comment by ilias-sp** [comment]
hi, 

Thank you for your kind words, glad its useful to you!

i tried your recommendation, to enable the extension mb_openssl, but it didnt help. i am still getting:

```
[Tue Mar 20 02:00:15 2018] 127.0.0.1:52395 Invalid request (Unsupported SSL request)
[Tue Mar 20 02:00:15 2018] 127.0.0.1:52396 Invalid request (Unsupported SSL request)
```

i did some googling, and stumbled on this [stackoverflow](https://stackoverflow.com/questions/12946486/openssl-not-working-with-php-built-in-webserver), that claims this extension is irrelevant to the builtin webserver of PHP.

To be honest, since the web interface is meant to run locally on the same PC as the bot does, the https is not that crucial.

thx
