### ISSUE TITLE
Get information if user is subscriber or not

### ISSUE THREAD

**Issue by ghost** [ilias-sp/Twitch-Chat-Bot-PHP#3]
I know this isn't an issue however I was wondering if you'd be able to share a method to getting if the user is a subscriber to the channel or not

Regards,

Ezit

**Comment by ilias-sp** [comment]
hi,

I will give it a try, and let you know in a few days, hopefully with positive results :)

**Comment by ilias-sp** [comment]
hi @xEzitx ,

so, i gave it a try and looks like the implementation can only work if the channel owner runs the bot under his own account. if you have a channel `xEzitx` and you have a separate account to run the bot - for example `xEzitx_Bot`, the Bot account wont be able to query your channels subscriptions. I am getting this response from the API:

> {"error":"Forbidden","status":403,"message":"Cannot view channel subscription of another user."}

So, not sure how useful this can be. 

Good news, is that i am now adding support to change stream title or game (this can be done only via Twitch API, and since we got to start using it, its now possible) :)

**Comment by ilias-sp** [comment]
check new version [v3.0.1](https://github.com/ilias-sp/Twitch-Chat-Bot-PHP/releases/tag/v3.0.1)
